### ISSUE TITLE
"export 'NgxGalleryAnimation' was not found in 'ngx-gallery-9'

### ISSUE THREAD

**Issue by hellseyfer** [SaeedSpate/ngx-gallery-9#1]
Hello and thanks for the plugin update,

just installed it on my recently upgraded angular 9 project and when I try to import to my ts component it says that there was no export for the 3 main modules:  **NgxGalleryOptions, NgxGalleryImage, NgxGalleryAnimation**

when I navigate to 'ngx-gallery-9' it shows me this:

/**
 * Generated bundle index. Do not edit.
 */
export * from './public-api';
export { NgxGalleryActionComponent as ɵe } from './lib/ngx-gallery-action/ngx-gallery-action.component';
export { NgxGalleryArrowsComponent as ɵf } from './lib/ngx-gallery-arrows/ngx-gallery-arrows.component';
export { NgxGalleryBulletsComponent as ɵg } from './lib/ngx-gallery-bullets/ngx-gallery-bullets.component';
export { NgxGalleryHelperService as ɵa } from './lib/ngx-gallery-helper.service';
export { NgxGalleryImageComponent as ɵc } from './lib/ngx-gallery-image/ngx-gallery-image.component';
export { NgxGalleryPreviewComponent as ɵb } from './lib/ngx-gallery-preview/ngx-gallery-preview.component';
export { NgxGalleryThumbnailsComponent as ɵd } from './lib/ngx-gallery-thumbnails/ngx-gallery-thumbnails.component';

**Comment by SaeedSpate** [comment]
Hello @hellseyfer, thanks for improving.
This issue is solved in [New version 1.0.6](https://www.npmjs.com/package/ngx-gallery-9), you can now update your package.json.
